plugins:
  onebox_assistant_enabled:
    default: true
    client: false
  onebox_assistant_always_use_proxy:
    default: false
    client: false
  onebox_assistant_api_base_address:
    default: ''
    client: false
  onebox_assistant_api_base_query:
    default: ''
    client: false
  onebox_assistant_api_options:
    default: ''
    client: false
  onebox_assistant_api_page_source_field:
      default: ''
      client: false
  onebox_assistant_api_key:
    default: ''
    client: false
